### ISSUE TITLE
前天可以直接部署成功的，今天无论部署自己的项目还是这个仓库的example，访问均报错

### ISSUE THREAD

**Issue by BetterLuke** [serverless-components/tencent-nestjs#12]
官方的大佬们，你们辛苦啦，我来问个问题，：前天可以直接部署成功的，今天无论部署自己的项目还是这个仓库的example，反访问均报错。想确认下是不是官方的更新导致来使用的策略的需要更新？
```
{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"83c121aa4997fa2c5a896e73b886c803","stackTrace":"Error: Cannot find module './dist/main'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.\u003canonymous\u003e (/var/user/sls.js:2:23)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)","statusCode":430}
```

如图：
![image](https://user-images.githubusercontent.com/12392903/112521948-0ae27e00-8dd8-11eb-9733-5ca40970f400.png)

然后，我机智的手动更改`sls.js`文件对于main.js的饮用为`./main`，然后访问API，又遇到：
`{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"bdf8ded6cccb010c557512c807b72b19","stackTrace":"Error: Cannot find module '@nestjs/core'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.\u003canonymous\u003e (/var/user/dist/main.js:4:16)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)","statusCode":430}`

一样上图：
![image](https://user-images.githubusercontent.com/12392903/112522979-36199d00-8dd9-11eb-96cf-b9de647b403c.png)

**Comment by BetterLuke** [comment]
> 官方的大佬们，你们辛苦啦，我来问个问题，：前天可以直接部署成功的，今天无论部署自己的项目还是这个仓库的example，反访问均报错。想确认下是不是官方的更新导致来使用的策略的需要更新？
> 
> ```
> {"errorCode":-1,"errorMessage":"user code exception caught","requestId":"83c121aa4997fa2c5a896e73b886c803","stackTrace":"Error: Cannot find module './dist/main'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n    at Module.require (internal/modules/cjs/loader.js:637:17)\n    at require (internal/modules/cjs/helpers.js:22:18)\n    at Object.\u003canonymous\u003e (/var/user/sls.js:2:23)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n    at Module.load (internal/modules/cjs/loader.js:600:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:531:3)","statusCode":430}
> ```
> 
> 如图：
> ![image](https://user-images.githubusercontent.com/12392903/112521948-0ae27e00-8dd8-11eb-9733-5ca40970f400.png)
> 
> 然后，我机智的手动更改`sls.js`文件对于main.js的饮用为`./main`，然后访问API，又遇到：
> `{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"bdf8ded6cccb010c557512c807b72b19","stackTrace":"Error: Cannot find module '@nestjs/core'\n at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)\n at Function.Module._load (internal/modules/cjs/loader.js:508:25)\n at Module.require (internal/modules/cjs/loader.js:637:17)\n at require (internal/modules/cjs/helpers.js:22:18)\n at Object.\u003canonymous\u003e (/var/user/dist/main.js:4:16)\n at Module._compile (internal/modules/cjs/loader.js:701:30)\n at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)\n at Module.load (internal/modules/cjs/loader.js:600:32)\n at tryModuleLoad (internal/modules/cjs/loader.js:539:12)\n at Function.Module._load (internal/modules/cjs/loader.js:531:3)","statusCode":430}`
> 
> 一样上图：
> ![image](https://user-images.githubusercontent.com/12392903/112522979-36199d00-8dd9-11eb-96cf-b9de647b403c.png)

已解决，我更改了serverless的name属性后重新部署就好了。简直神奇哈哈哈。PS，我有曾经尝试`sls remove` 后再次，`sls deploy`，但还是一样但错误，我更改name属性后，就好了。

注：猜测可能和自己手动删除bucket里的代码文件有关。
